# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBoxSIFT = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSIFT.setGeometry(QtCore.QRect(50, 60, 281, 501))
        self.groupBoxSIFT.setObjectName("groupBoxSIFT")
        self.pushButtonLoadImage1 = QtWidgets.QPushButton(self.groupBoxSIFT)
        self.pushButtonLoadImage1.setGeometry(QtCore.QRect(30, 70, 211, 51))
        self.pushButtonLoadImage1.setObjectName("pushButtonLoadImage1")
        self.pushButtonShowKeypoints = QtWidgets.QPushButton(self.groupBoxSIFT)
        self.pushButtonShowKeypoints.setGeometry(QtCore.QRect(30, 300, 211, 51))
        self.pushButtonShowKeypoints.setObjectName("pushButtonShowKeypoints")
        self.pushButtonLoadImage2 = QtWidgets.QPushButton(self.groupBoxSIFT)
        self.pushButtonLoadImage2.setGeometry(QtCore.QRect(30, 180, 211, 51))
        self.pushButtonLoadImage2.setObjectName("pushButtonLoadImage2")
        self.pushButtonShowMatchedKeypoints = QtWidgets.QPushButton(self.groupBoxSIFT)
        self.pushButtonShowMatchedKeypoints.setGeometry(QtCore.QRect(30, 410, 211, 51))
        self.pushButtonShowMatchedKeypoints.setObjectName("pushButtonShowMatchedKeypoints")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2022 CvDl Hw1_04"))
        self.groupBoxSIFT.setTitle(_translate("MainWindow", "4. SIFT"))
        self.pushButtonLoadImage1.setText(_translate("MainWindow", "Load Image 1"))
        self.pushButtonShowKeypoints.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.pushButtonLoadImage2.setText(_translate("MainWindow", "Load Image 2"))
        self.pushButtonShowMatchedKeypoints.setText(_translate("MainWindow", "4.2 Matched Keypoints"))
